spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.17/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug